server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: docker-logs
  docker_sd_configs:
    - host: "unix:///var/run/docker.sock"
      refresh_interval: 5s
      filters:
        - name: label
          values: ["com.docker.compose.service=app"]

  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      target_label: 'container'
    - source_labels: ['__meta_docker_compose_project']
      target_label: 'project'
    - source_labels: ['__meta_docker_compose_service']
      target_label: 'service'